name: CI
on:
  push:
    branches:
      - '**'

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install packages
        uses: ./.github/actions/setup-npm

      - name: Compile
        run: npm run compile

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
