name: Create Release
on: workflow_dispatch

jobs:
  create-release:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    env:
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: 'master'

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'

      - name: Install packages
        uses: ./.github/actions/setup-npm
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Create Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v6
        with:
          github-token: ${{ secrets.github_token }}
          git-message: 'chore: release'
          git-user-name: 'janro1'
          git-user-email: 'code@jannorothfos.com'
          config-file-path: './changelog.config.cjs'

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: npm publish --provenance --access public

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
