name: Create Release
on: workflow_dispatch

jobs:
  create-release:
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_TOKEN }}
          ref: 'master'

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install packages
        uses: ./.github/actions/setup-npm
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Create Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.REPO_TOKEN }}
          git-message: 'chore: release'
          git-user-name: 'janro1'
          git-user-email: 'code@jannorothfos.com'
          config-file-path: './changelog.config.js'

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: npm publish --access public

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN  }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
